development:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

  site_name: Event Thing
  site_url: "http://localhost:3000"

  themes: ["Community Action", "Food and Cookery", "Languages and Travel", "Heritage and History", "Culture, Arts & Crafts", "Music and Performing Arts", "Sport and Physical Activity", "Health and Wellbeing", "Nature & the Environment", "Technology & Broadcasting", "Other"]
  types: ["Workshop", "Taster Session", "Exhibition", "Mini-project", "Competition", "Performance", "Demonstration", "Display", "Class", "Other"]

test:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

  site_name: Event Thing
  site_url: "http://localhost:3000"

  themes: ["Community Action", "Food and Cookery", "Languages and Travel", "Heritage and History", "Culture, Arts & Crafts", "Music and Performing Arts", "Sport and Physical Activity", "Health and Wellbeing", "Nature & the Environment", "Technology & Broadcasting", "Other"]
  types: ["Workshop", "Taster Session", "Exhibition", "Mini-project", "Competition", "Performance", "Demonstration", "Display", "Class", "Other"]

production:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

  site_name: Event Thing
  site_url: "http://localhost:3000"

  themes: ["Community Action", "Food and Cookery", "Languages and Travel", "Heritage and History", "Culture, Arts & Crafts", "Music and Performing Arts", "Sport and Physical Activity", "Health and Wellbeing", "Nature & the Environment", "Technology & Broadcasting", "Other"]
  types: ["Workshop", "Taster Session", "Exhibition", "Mini-project", "Competition", "Performance", "Demonstration", "Display", "Class", "Other"]
