development:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  google_maps_key: ABQIAAAA9hPO1yRskyJFY-uwV_gAqhS6yI4Oky2btJnizjKkhx0I2b61jBSWUb_l1DnqFARJb38kjFSVsk0Bcw  
  badge: badges
  
  contact_email: learningrevolution@bis.gsi.gov.uk

test:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub  
  
  google_maps_key: ABQIAAAA9hPO1yRskyJFY-uwV_gAqhS6yI4Oky2btJnizjKkhx0I2b61jBSWUb_l1DnqFARJb38kjFSVsk0Bcw
  badge: badges
  
  contact_email: learningrevolution@bis.gsi.gov.uk

production:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://learningrevolution.direct.gov.uk

  event_uri_template: /events/:year/:month/:day/:stub
  
  google_maps_key: ABQIAAAA9hPO1yRskyJFY-uwV_gAqhS6yI4Oky2btJnizjKkhx0I2b61jBSWUb_l1DnqFARJb38kjFSVsk0Bcw  
  badge: badges
  
  contact_email: learningrevolution@bis.gsi.gov.uk
