development:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

  site_name: Event Thing
  site_url: "http://localhost:3000"

test:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

  site_name: Event Thing
  site_url: "http://localhost:3000"

production:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

  site_name: Event Thing
  site_url: "http://localhost:3000"
