development:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

test:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 

production:
  bitly_account: 
  bitly_api_key: 

  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:

  badge: badges

  contact_email: x@example.org

  upcoming_api_key: 
  upcoming_api_token: 
