development:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub

  yahoo_api_key:
  google_maps_key:
    
  badge: badges
  
  contact_email: learningrevolution@bis.gsi.gov.uk
  
  upcoming_api_key: c5771340a8
  upcoming_api_token: 15ba9abf19892e6d32a27bd717c564239818c62b

test:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub  
  
  yahoo_api_key: 7SI401vV34HiBOmMRY1Hj.7N_NFTn5oA_oAD9gys99MHdRyFGKkHEy1bMmOfhlw-
  google_maps_key: ABQIAAAA9hPO1yRskyJFY-uwV_gAqhS6yI4Oky2btJnizjKkhx0I2b61jBSWUb_l1DnqFARJb38kjFSVsk0Bcw
  badge: badges
  
  contact_email: learningrevolution@bis.gsi.gov.uk
  
  upcoming_api_key: 
  upcoming_api_token: 

production:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://learningrevolution.direct.gov.uk

  event_uri_template: /events/:year/:month/:day/:stub
  
  yahoo_api_key: 7SI401vV34HiBOmMRY1Hj.7N_NFTn5oA_oAD9gys99MHdRyFGKkHEy1bMmOfhlw-
  google_maps_key: ABQIAAAA9hPO1yRskyJFY-uwV_gAqhTIXty0RZjPK94OBBEAE5LamIlH1hRE7kn2Ml0WJdYWkdaP0uVM86K3jQ  
  badge: badges
  
  contact_email: learningrevolution@bis.gsi.gov.uk
  
  upcoming_api_key: 
  upcoming_api_token: 
