development:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub
  
test:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://localhost

  event_uri_template: /events/:year/:month/:day/:stub  

production:
  bitly_account: learningrevolution
  bitly_api_key: R_3440f2303ec9952df2250801cfba4baa
  
  bitly_target_host: http://learningrevolution.direct.gov.uk

  event_uri_template: /events/:year/:month/:day/:stub
  
