Page.create!(:slug => "about", :title => "About", :content => "<p>Blah blah blah.</p>")
Page.create!(:slug => "resources", :title => "Resources", :content => "<p>Sample content goes here.</p>")
Page.create!(:slug => "terms-conditions", :title => "Terms and Conditions", :content => "<p>Lots of legalese.</p><p>You give us the right to publish your event. Duh.</p>")
Page.create!(:slug => "privacy", :title => "Your Privacy", :content => "<p>Moar legalese.</p><p>we pwn all joo's data</p>")
Page.create!(:slug => "promote-your-event", :title => "Promote Your Event", :content => "<p>Promote it. Promote!</p>")
