#!/bin/sh

# For a list of broken lists, look at the bottom of log/wget and log/wget-admin

wget --spider --recursive http://lain:3000/ -o log/wget
wget --spider --recursive --user=lr_admin --password='learning is fun!' http://lain:3000/admin -o log/wget-admin
